name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          enable-deltas-report: true
          fqbn: esp32-bluepad32:esp32:esp32da
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./slider
          libraries: |
            - name: LiquidCrystal I2C
            - name: AccelStepper
            - name: Preferences
            - name: WiFi
          platforms: |
            # Install the platform from the root of the repository, replacing the BM installed platform
            - name: "esp32:esp32"
              source-url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
            # Install the platform from the root of the repository, replacing the BM installed platform
            - name: "esp32-bluepad32:esp32"
              source-url: "https://raw.githubusercontent.com/ricardoquesada/esp32-arduino-lib-builder/master/bluepad32_files/package_esp32_bluepad32_index.json"
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: sketches-reports
          path: sketches-reports

  report:
    permissions: 
      pull-requests: write
    needs: compile-sketch # Wait for the compile job to finish to get the data for the report
    if: github.event_name == 'pull_request' # Only run the job when the workflow is triggered by a pull request
    runs-on: ubuntu-latest
    steps:
        # This step is needed to get the size data produced by the compile jobs
        - name: Download sketches reports artifacts
          uses: actions/download-artifact@v4
          with:
            path: sketches-reports
        - uses: arduino/report-size-deltas@v1
          with:
            sketches-reports-source: sketches-reports